"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.movies = exports.numMainActors = void 0;
const [action, comedy, drama, fantasy, horror, scifi, thriller, western, sports,] = [0, 1, 2, 3, 4, 5, 6, 7, 8];
exports.numMainActors = 10;
exports.movies = [
    {
        showtimes: [2, 3.5],
        runningTime: 2.3,
        genres: [action, drama],
        mainActors: [2, 4],
        availableTickets: 87,
    },
    {
        showtimes: [1, 4],
        runningTime: 1.8,
        genres: [comedy],
        mainActors: [0, 3],
        availableTickets: 42,
    },
    {
        showtimes: [2.5, 5],
        runningTime: 2.1,
        genres: [scifi, action],
        mainActors: [1, 5],
        availableTickets: 115,
    },
    {
        showtimes: [3, 6],
        runningTime: 1.5,
        genres: [horror],
        mainActors: [6, 9],
        availableTickets: 9,
    },
    {
        showtimes: [1.5, 4.5],
        runningTime: 2.0,
        genres: [drama],
        mainActors: [2, 7],
        availableTickets: 63,
    },
    {
        showtimes: [2, 5.5],
        runningTime: 2.4,
        genres: [thriller],
        mainActors: [3, 8],
        availableTickets: 130,
    },
    {
        showtimes: [1, 3, 6],
        runningTime: 1.9,
        genres: [comedy],
        mainActors: [0, 4],
        availableTickets: 77,
    },
    {
        showtimes: [2.5, 5],
        runningTime: 2.2,
        genres: [fantasy],
        mainActors: [5, 9],
        availableTickets: 24,
    },
    {
        showtimes: [3, 6.5],
        runningTime: 2.7,
        genres: [scifi],
        mainActors: [1, 6],
        availableTickets: 98,
    },
    {
        showtimes: [1, 4, 7],
        runningTime: 1.6,
        genres: [western],
        mainActors: [7, 2],
        availableTickets: 145,
    },
    {
        showtimes: [2, 5],
        runningTime: 2.0,
        genres: [sports, drama],
        mainActors: [3, 8],
        availableTickets: 55,
    },
    {
        showtimes: [1.5, 4],
        runningTime: 1.8,
        genres: [action, thriller],
        mainActors: [4, 9],
        availableTickets: 12,
    },
    {
        showtimes: [3, 6],
        runningTime: 2.3,
        genres: [horror, thriller],
        mainActors: [0, 5],
        availableTickets: 101,
    },
    {
        showtimes: [2, 4.5],
        runningTime: 2.1,
        genres: [comedy],
        mainActors: [1, 6],
        availableTickets: 68,
    },
    {
        showtimes: [1, 3.5, 6],
        runningTime: 1.7,
        genres: [drama],
        mainActors: [2, 7],
        availableTickets: 33,
    },
    {
        showtimes: [2.5, 5.5],
        runningTime: 2.5,
        genres: [fantasy, action],
        mainActors: [3, 8],
        availableTickets: 149,
    },
    {
        showtimes: [1, 4],
        runningTime: 1.9,
        genres: [scifi, thriller],
        mainActors: [4, 9],
        availableTickets: 0,
    },
    {
        showtimes: [3, 6],
        runningTime: 2.2,
        genres: [western, action],
        mainActors: [5, 0],
        availableTickets: 82,
    },
    {
        showtimes: [2, 5],
        runningTime: 1.8,
        genres: [sports],
        mainActors: [6, 1],
        availableTickets: 119,
    },
    {
        showtimes: [1.5, 4.5],
        runningTime: 2.6,
        genres: [horror],
        mainActors: [7, 2],
        availableTickets: 37,
    },
    {
        showtimes: [2, 5],
        runningTime: 2.0,
        genres: [drama, thriller],
        mainActors: [8, 3],
        availableTickets: 74,
    },
    {
        showtimes: [1, 3, 6.5],
        runningTime: 1.7,
        genres: [comedy, action],
        mainActors: [9, 4],
        availableTickets: 6,
    },
    {
        showtimes: [2.5, 5],
        runningTime: 2.3,
        genres: [fantasy, scifi],
        mainActors: [0, 5],
        availableTickets: 93,
    },
    {
        showtimes: [3, 6],
        runningTime: 1.9,
        genres: [drama],
        mainActors: [1, 6],
        availableTickets: 128,
    },
    {
        showtimes: [1, 4],
        runningTime: 2.1,
        genres: [action],
        mainActors: [2, 7],
        availableTickets: 51,
    },
    {
        showtimes: [2, 5.5],
        runningTime: 2.4,
        genres: [horror, scifi],
        mainActors: [3, 8],
        availableTickets: 18,
    },
    {
        showtimes: [1.5, 4],
        runningTime: 1.6,
        genres: [comedy],
        mainActors: [4, 9],
        availableTickets: 107,
    },
    {
        showtimes: [3, 6],
        runningTime: 2.8,
        genres: [western, drama],
        mainActors: [5, 0],
        availableTickets: 44,
    },
    {
        showtimes: [2, 5],
        runningTime: 2.0,
        genres: [thriller, action],
        mainActors: [6, 1],
        availableTickets: 136,
    },
    {
        showtimes: [1, 3.5],
        runningTime: 1.8,
        genres: [sports, comedy],
        mainActors: [7, 2],
        availableTickets: 29,
    },
    {
        showtimes: [2.5, 5.5],
        runningTime: 2.2,
        genres: [fantasy],
        mainActors: [8, 3],
        availableTickets: 88,
    },
    {
        showtimes: [1, 4, 7],
        runningTime: 1.9,
        genres: [scifi],
        mainActors: [9, 4],
        availableTickets: 3,
    },
    {
        showtimes: [3, 6],
        runningTime: 2.5,
        genres: [drama, horror],
        mainActors: [0, 5],
        availableTickets: 122,
    },
    {
        showtimes: [2, 5],
        runningTime: 1.7,
        genres: [comedy, thriller],
        mainActors: [1, 6],
        availableTickets: 61,
    },
    {
        showtimes: [1.5, 4.5],
        runningTime: 2.3,
        genres: [action, scifi],
        mainActors: [2, 7],
        availableTickets: 80,
    },
    {
        showtimes: [2, 5],
        runningTime: 2.0,
        genres: [western],
        mainActors: [3, 8],
        availableTickets: 15,
    },
    {
        showtimes: [1, 3, 6],
        runningTime: 1.8,
        genres: [sports, drama],
        mainActors: [4, 9],
        availableTickets: 143,
    },
    {
        showtimes: [2.5, 5],
        runningTime: 2.6,
        genres: [horror],
        mainActors: [5, 0],
        availableTickets: 48,
    },
    {
        showtimes: [3, 6.5],
        runningTime: 2.1,
        genres: [fantasy, drama],
        mainActors: [6, 1],
        availableTickets: 97,
    },
    {
        showtimes: [1, 4],
        runningTime: 1.9,
        genres: [action, comedy],
        mainActors: [7, 2],
        availableTickets: 72,
    },
    {
        showtimes: [2, 5.5],
        runningTime: 2.4,
        genres: [thriller, horror],
        mainActors: [8, 3],
        availableTickets: 21,
    },
    {
        showtimes: [1.5, 4],
        runningTime: 1.7,
        genres: [scifi, fantasy],
        mainActors: [9, 4],
        availableTickets: 110,
    },
    {
        showtimes: [3, 6],
        runningTime: 2.2,
        genres: [drama],
        mainActors: [0, 5],
        availableTickets: 39,
    },
    {
        showtimes: [2, 5],
        runningTime: 1.8,
        genres: [comedy, sports],
        mainActors: [1, 6],
        availableTickets: 126,
    },
    {
        showtimes: [1, 3.5, 6.5],
        runningTime: 2.0,
        genres: [action, western],
        mainActors: [2, 7],
        availableTickets: 57,
    },
    {
        showtimes: [2.5, 5],
        runningTime: 2.7,
        genres: [horror, fantasy],
        mainActors: [3, 8],
        availableTickets: 84,
    },
    {
        showtimes: [1, 4],
        runningTime: 1.6,
        genres: [thriller],
        mainActors: [4, 9],
        availableTickets: 11,
    },
    {
        showtimes: [3, 6],
        runningTime: 2.3,
        genres: [sports],
        mainActors: [5, 0],
        availableTickets: 138,
    },
    {
        showtimes: [2, 5],
        runningTime: 2.1,
        genres: [drama, comedy],
        mainActors: [6, 1],
        availableTickets: 66,
    },
    {
        showtimes: [1.5, 4.5],
        runningTime: 1.9,
        genres: [scifi, action],
        mainActors: [7, 2],
        availableTickets: 103,
    },
    {
        showtimes: [2, 5.5],
        runningTime: 2.5,
        genres: [fantasy, thriller],
        mainActors: [8, 3],
        availableTickets: 27,
    },
    {
        showtimes: [1, 3, 6],
        runningTime: 1.8,
        genres: [horror],
        mainActors: [9, 4],
        availableTickets: 92,
    },
    {
        showtimes: [2.5, 5],
        runningTime: 2.0,
        genres: [western, comedy],
        mainActors: [0, 5],
        availableTickets: 46,
    },
    {
        showtimes: [3, 6.5],
        runningTime: 2.2,
        genres: [drama, sports],
        mainActors: [1, 6],
        availableTickets: 117,
    },
    {
        showtimes: [1, 4],
        runningTime: 1.7,
        genres: [action, thriller],
        mainActors: [2, 7],
        availableTickets: 35,
    },
    {
        showtimes: [2, 5],
        runningTime: 2.6,
        genres: [scifi, horror],
        mainActors: [3, 8],
        availableTickets: 78,
    },
    {
        showtimes: [1.5, 4],
        runningTime: 2.0,
        genres: [comedy],
        mainActors: [4, 9],
        availableTickets: 5,
    },
    {
        showtimes: [3, 6],
        runningTime: 2.3,
        genres: [fantasy, action],
        mainActors: [5, 0],
        availableTickets: 141,
    },
    {
        showtimes: [2, 5.5],
        runningTime: 1.8,
        genres: [drama, thriller],
        mainActors: [6, 1],
        availableTickets: 53,
    },
    {
        showtimes: [1, 3.5],
        runningTime: 2.1,
        genres: [sports, action],
        mainActors: [7, 2],
        availableTickets: 99,
    },
    {
        showtimes: [2.5, 5],
        runningTime: 2.4,
        genres: [horror, drama],
        mainActors: [8, 3],
        availableTickets: 20,
    },
    {
        showtimes: [1, 4, 7],
        runningTime: 1.9,
        genres: [western, thriller],
        mainActors: [9, 4],
        availableTickets: 113,
    },
    {
        showtimes: [3, 6],
        runningTime: 2.2,
        genres: [scifi, comedy],
        mainActors: [0, 5],
        availableTickets: 70,
    },
    {
        showtimes: [2, 5],
        runningTime: 1.7,
        genres: [action],
        mainActors: [1, 6],
        availableTickets: 31,
    },
    {
        showtimes: [1.5, 4.5],
        runningTime: 2.5,
        genres: [fantasy, horror],
        mainActors: [2, 7],
        availableTickets: 147,
    },
    {
        showtimes: [2, 5.5],
        runningTime: 2.0,
        genres: [drama],
        mainActors: [3, 8],
        availableTickets: 59,
    },
    {
        showtimes: [1, 3, 6],
        runningTime: 1.8,
        genres: [comedy, drama],
        mainActors: [4, 9],
        availableTickets: 86,
    },
    {
        showtimes: [2.5, 5],
        runningTime: 2.3,
        genres: [thriller, scifi],
        mainActors: [5, 0],
        availableTickets: 14,
    },
    {
        showtimes: [3, 6.5],
        runningTime: 1.6,
        genres: [sports, comedy],
        mainActors: [6, 1],
        availableTickets: 104,
    },
    {
        showtimes: [1, 4],
        runningTime: 2.1,
        genres: [horror, action],
        mainActors: [7, 2],
        availableTickets: 43,
    },
    {
        showtimes: [2, 5],
        runningTime: 2.7,
        genres: [fantasy, drama],
        mainActors: [8, 3],
        availableTickets: 132,
    },
    {
        showtimes: [1.5, 4],
        runningTime: 1.9,
        genres: [western, action],
        mainActors: [9, 4],
        availableTickets: 67,
    },
    {
        showtimes: [3, 6],
        runningTime: 2.0,
        genres: [drama, scifi],
        mainActors: [0, 5],
        availableTickets: 8,
    },
    {
        showtimes: [2, 5.5],
        runningTime: 1.8,
        genres: [comedy, horror],
        mainActors: [1, 6],
        availableTickets: 120,
    },
    {
        showtimes: [1, 3.5, 6.5],
        runningTime: 2.4,
        genres: [action, sports],
        mainActors: [2, 7],
        availableTickets: 76,
    },
    {
        showtimes: [2.5, 5],
        runningTime: 2.2,
        genres: [thriller],
        mainActors: [3, 8],
        availableTickets: 23,
    },
    {
        showtimes: [1, 4],
        runningTime: 1.7,
        genres: [scifi, western],
        mainActors: [4, 9],
        availableTickets: 95,
    },
    {
        showtimes: [3, 6],
        runningTime: 2.5,
        genres: [horror, comedy],
        mainActors: [5, 0],
        availableTickets: 50,
    },
    {
        showtimes: [2, 5],
        runningTime: 2.0,
        genres: [fantasy],
        mainActors: [6, 1],
        availableTickets: 139,
    },
    {
        showtimes: [1.5, 4.5],
        runningTime: 1.9,
        genres: [drama, action],
        mainActors: [7, 2],
        availableTickets: 62,
    },
    {
        showtimes: [2, 5.5],
        runningTime: 2.3,
        genres: [sports, thriller],
        mainActors: [8, 3],
        availableTickets: 17,
    },
    {
        showtimes: [1, 3, 6],
        runningTime: 1.8,
        genres: [comedy, scifi],
        mainActors: [9, 4],
        availableTickets: 108,
    },
    {
        showtimes: [2.5, 5],
        runningTime: 2.6,
        genres: [horror, western],
        mainActors: [0, 5],
        availableTickets: 34,
    },
    {
        showtimes: [3, 6.5],
        runningTime: 2.1,
        genres: [drama, fantasy],
        mainActors: [1, 6],
        availableTickets: 125,
    },
    {
        showtimes: [1, 4],
        runningTime: 1.7,
        genres: [action, comedy],
        mainActors: [2, 7],
        availableTickets: 71,
    },
    {
        showtimes: [2, 5],
        runningTime: 2.2,
        genres: [thriller, drama],
        mainActors: [3, 8],
        availableTickets: 2,
    },
    {
        showtimes: [1.5, 4],
        runningTime: 2.0,
        genres: [scifi],
        mainActors: [4, 9],
        availableTickets: 90,
    },
    {
        showtimes: [3, 6],
        runningTime: 1.8,
        genres: [sports, western],
        mainActors: [5, 0],
        availableTickets: 116,
    },
    {
        showtimes: [2, 5.5],
        runningTime: 2.4,
        genres: [fantasy, comedy],
        mainActors: [6, 1],
        availableTickets: 45,
    },
    {
        showtimes: [1, 3.5],
        runningTime: 1.9,
        genres: [horror, thriller],
        mainActors: [7, 2],
        availableTickets: 133,
    },
    {
        showtimes: [2.5, 5],
        runningTime: 2.1,
        genres: [action, drama],
        mainActors: [8, 3],
        availableTickets: 58,
    },
    {
        showtimes: [1, 4, 7],
        runningTime: 1.6,
        genres: [comedy],
        mainActors: [9, 4],
        availableTickets: 83,
    },
    {
        showtimes: [3, 6],
        runningTime: 2.3,
        genres: [scifi, drama],
        mainActors: [0, 5],
        availableTickets: 26,
    },
    {
        showtimes: [2, 5],
        runningTime: 2.0,
        genres: [western, horror],
        mainActors: [1, 6],
        availableTickets: 150,
    },
    {
        showtimes: [1.5, 4.5],
        runningTime: 2.5,
        genres: [sports, scifi],
        mainActors: [2, 7],
        availableTickets: 40,
    },
    {
        showtimes: [2, 5.5],
        runningTime: 1.8,
        genres: [drama, thriller],
        mainActors: [3, 8],
        availableTickets: 106,
    },
    {
        showtimes: [1, 3, 6],
        runningTime: 2.2,
        genres: [fantasy, action],
        mainActors: [4, 9],
        availableTickets: 69,
    },
];
